"""Game constants and configuration."""

SCREEN_WIDTH = 400
SCREEN_HEIGHT = 600
SPEED = 20
GRAVITY = 2
GAME_SPEED = 15
FPS = 15

GROUND_WIDTH = 2 * SCREEN_WIDTH
GROUND_HEIGHT = 100

PIPE_WIDTH = 80
PIPE_HEIGHT = 500
PIPE_GAP = 150
PIPE_MIN_SIZE = 100
PIPE_MAX_SIZE = 300

BEGIN_IMAGE_X = 120
BEGIN_IMAGE_Y = 150

# AUDIO PATHS
WING_SOUND = "assets/audio/wing.wav"
HIT_SOUND = "assets/audio/hit.wav"
